
// gender options
export const genderOptions = [
	{value: 'male', label: 'Male'},
	{value: 'female', label: 'Female'},
	{value: 'other', label: 'Other'}
]

// genre options
export const genreOptions = [
	{ value: 'rock', label: 'Rock' },
	{ value: 'pop', label: 'Pop' },
	{ value: 'jazz', label: 'Jazz' },
	{ value: 'hip-hop', label: 'Hip-Hop' },
	{ value: 'classical', label: 'Classical' },
	{ value: 'blues', label: 'Blues' },
	{ value: 'reggae', label: 'Reggae' },
	{ value: 'metal', label: 'Metal' },
	{ value: 'country', label: 'Country' },
	{ value: 'electronic', label: 'Electronic' },
	{ value: 'folk', label: 'Folk' },
	{ value: 'funk', label: 'Funk' },
	{ value: 'soul', label: 'Soul' },
	{ value: 'punk', label: 'Punk' },
	{ value: 'rnb', label: 'R&B' },
	{ value: 'house', label: 'House' },
	{ value: 'techno', label: 'Techno' },
	{ value: 'indie', label: 'Indie' },
	{ value: 'gospel', label: 'Gospel' },
	{ value: 'ska', label: 'Ska' },
	{ value: 'other', label: 'Other' }
];

// method options
export const methodsOptions = [
	{ value: 'singing', label: 'Singing' },
	{ value: 'djing', label: 'Live DJing/Remixing' },
	{ value: 'piano', label: 'Piano' },
	{ value: 'guitar', label: 'Guitar' },
	{ value: 'bass', label: 'Bass Guitar' },
	{ value: 'drums', label: 'Drums/Percussion' },
	{ value: 'violin', label: 'Violin/Strings' },
	{ value: 'saxophone', label: 'Saxophone/Brass' },
	{ value: 'flute', label: 'Flute/Other Woodwinds' },
	{ value: 'harp', label: 'Harp' },
	{ value: 'harmonica', label: 'Harmonica' },
	{ value: 'accordion', label: 'Accordion' },
	{ value: 'ukulele', label: 'Ukulele' },
	{ value: 'keyboard', label: 'Keyboard/Synthesizers' },
	{ value: 'cello', label: 'Cello' },
	{ value: 'sampling', label: 'Sampling' },
	{ value: 'beatmaking', label: 'Beatmaking' },
	{ value: 'looping', label: 'Looping' },
	{ value: 'sound_design', label: 'Sound Design' },
	{ value: 'midi', label: 'MIDI Production' },
	{ value: 'vocoder', label: 'Vocoder' },
	{ value: 'electronic_drums', label: 'Electronic Drums' },
	{ value: 'beatboxing', label: 'Beatboxing' },
	{ value: 'acapella', label: 'Acapella' },
	{ value: 'rapping', label: 'Rapping' },
	{ value: 'screaming', label: 'Screaming/Harsh Vocals' },
	{ value: 'falsetto', label: 'Falsetto' },
	{ value: 'head_voice', label: 'Head Voice' },
	{ value: 'harmonizing', label: 'Harmonizing' },
	{ value: 'whispering', label: 'Whispering' },
	{ value: 'voice_processing', label: 'Voice Processing' },
	{ value: 'melismatic_singing', label: 'Melismatic Singing' },
	{ value: 'field_recording', label: 'Field Recording' },
	{ value: 'found_sounds', label: 'Found Sounds' },
	{ value: 'sound_collage', label: 'Sound Collage' },
	{ value: 'live_instrumentation', label: 'Live Instrumentation' },
	{ value: 'foley', label: 'Foley' },
	{ value: 'other', label: 'Other'}
];
// interest options
export const interestsOptions = [
	{ value: 'sports', label: 'Sports' },
	{ value: 'movies', label: 'Movies' },
	{ value: 'books', label: 'Books' },
	{ value: 'technology', label: 'Technology' },
	{ value: 'travel', label: 'Travel' },
	{ value: 'gaming', label: 'Gaming' },
	{ value: 'photography', label: 'Photography' },
	{ value: 'art', label: 'Art' },
	{ value: 'fitness', label: 'Fitness' },
	{ value: 'cooking', label: 'Cooking' },
	{ value: 'fashion', label: 'Fashion' },
	{ value: 'history', label: 'History' },
	{ value: 'politics', label: 'Politics' },
	{ value: 'education', label: 'Education' },
	{ value: 'science', label: 'Science' },
	{ value: 'environment', label: 'Environment' },
	{ value: 'nature', label: 'Nature' },
	{ value: 'animals', label: 'Animals' },
	{ value: 'writing', label: 'Writing' },
	{ value: 'poetry', label: 'Poetry' },
	{ value: 'theater', label: 'Theater' },
	{ value: 'comedy', label: 'Comedy' },
	{ value: 'dancing', label: 'Dancing' },
	{ value: 'gardening', label: 'Gardening' },
	{ value: 'crafting', label: 'Crafting' },
	{ value: 'photography', label: 'Photography' },
	{ value: 'health', label: 'Health' },
	{ value: 'mental_health', label: 'Mental Health' },
	{ value: 'self_improvement', label: 'Self Improvement' },
	{ value: 'spirituality', label: 'Spirituality' },
	{ value: 'philanthropy', label: 'Philanthropy' },
	{ value: 'social_media', label: 'Social Media' },
	{ value: 'entrepreneurship', label: 'Entrepreneurship' },
	{ value: 'marketing', label: 'Marketing' },
	{ value: 'finance', label: 'Finance' },
	{ value: 'investing', label: 'Investing' },
	{ value: 'real_estate', label: 'Real Estate' },
	{ value: 'craft_beer', label: 'Craft Beer' },
	{ value: 'wine', label: 'Wine' },
	{ value: 'cocktails', label: 'Cocktails' },
	{ value: 'board_games', label: 'Board Games' },
	{ value: 'esports', label: 'Esports' },
	{ value: 'virtual_reality', label: 'Virtual Reality' },
	{ value: 'augmented_reality', label: 'Augmented Reality' },
	{ value: 'fashion_design', label: 'Fashion Design' },
	{ value: 'interior_design', label: 'Interior Design' },
	{ value: 'architecture', label: 'Architecture' },
	{ value: 'astronomy', label: 'Astronomy' },
	{ value: 'space', label: 'Space' },
	{ value: 'robotics', label: 'Robotics' },
	{ value: 'fishing', label: 'Fishing' },
	{ value: 'hiking', label: 'Hiking' },
	{ value: 'cycling', label: 'Cycling' },
	{ value: 'other', label: 'Other' }
];

// personality options
export const personalityTraitsOptions = [
	{ value: 'introverted', label: 'Introverted' },
	{ value: 'extroverted', label: 'Extroverted' },
	{ value: 'optimistic', label: 'Optimistic' },
	{ value: 'pessimistic', label: 'Pessimistic' },
	{ value: 'creative', label: 'Creative' },
	{ value: 'analytical', label: 'Analytical' },
	{ value: 'empathetic', label: 'Empathetic' },
	{ value: 'independent', label: 'Independent' },
	{ value: 'dependable', label: 'Dependable' },
	{ value: 'adaptable', label: 'Adaptable' },
	{ value: 'organized', label: 'Organized' },
	{ value: 'spontaneous', label: 'Spontaneous' },
	{ value: 'confident', label: 'Confident' },
	{ value: 'humble', label: 'Humble' },
	{ value: 'reliable', label: 'Reliable' },
	{ value: 'loyal', label: 'Loyal' },
	{ value: 'honest', label: 'Honest' },
	{ value: 'compassionate', label: 'Compassionate' },
	{ value: 'curious', label: 'Curious' },
	{ value: 'patient', label: 'Patient' },
	{ value: 'ambitious', label: 'Ambitious' },
	{ value: 'passionate', label: 'Passionate' },
	{ value: 'self-disciplined', label: 'Self-Disciplined' },
	{ value: 'funny', label: 'Funny' },
	{ value: 'sarcastic', label: 'Sarcastic' },
	{ value: 'moody', label: 'Moody' },
	{ value: 'impulsive', label: 'Impulsive' },
	{ value: 'emotional', label: 'Emotional' },
	{ value: 'stubborn', label: 'Stubborn' },
	{ value: 'practical', label: 'Practical' },
	{ value: 'realistic', label: 'Realistic' },
	{ value: 'generous', label: 'Generous' },
	{ value: 'self-sufficient', label: 'Self-Sufficient' },
	{ value: 'sensitive', label: 'Sensitive' },
	{ value: 'enthusiastic', label: 'Enthusiastic' },
	{ value: 'open-minded', label: 'Open-Minded' },
	{ value: 'humorous', label: 'Humorous' },
	{ value: 'thoughtful', label: 'Thoughtful' },
	{ value: 'meticulous', label: 'Meticulous' },
	{ value: 'impassioned', label: 'Impassioned' },
	{ value: 'tolerant', label: 'Tolerant' },
	{ value: 'disciplined', label: 'Disciplined' },
	{ value: 'sociable', label: 'Sociable' },
	{ value: 'resourceful', label: 'Resourceful' },
	{ value: 'visionary', label: 'Visionary' },
	{ value: 'persuasive', label: 'Persuasive' },
	{ value: 'polite', label: 'Polite' },
	{ value: 'humble', label: 'Humble' },
	{ value: 'forgiving', label: 'Forgiving' },
	{ value: 'assertive', label: 'Assertive' },
	{ value: 'inquisitive', label: 'Inquisitive' },
	{ value: 'caring', label: 'Caring' },
	{ value: 'decisive', label: 'Decisive' },
	{ value: 'generous', label: 'Generous' }
];

// goals options
export const goalsOptions = [
	{ value: 'have_fun', label: 'Have Fun' },
	{ value: 'make_a_band', label: 'Make a Band' },
	{ value: 'build_a_career', label: 'Build a Career' },
	{ value: 'collaborate_on_projects', label: 'Collaborate on Projects' },
	{ value: 'learn_new_skills', label: 'Learn New Skills' },
	{ value: 'perform_live', label: 'Perform Live' },
	{ value: 'write_original_music', label: 'Write Original Music' },
	{ value: 'record_music', label: 'Record Music' },
	{ value: 'experiment_with_genres', label: 'Experiment with Genres' },
	{ value: 'create_impactful_music', label: 'Create Impactful Music' },
	{ value: 'improve_technique', label: 'Improve Technique' },
	{ value: 'network_in_music_industry', label: 'Network in the Music Industry' },
	{ value: 'make_music_videos', label: 'Make Music Videos' },
	{ value: 'gain_exposure', label: 'Gain Exposure' },
	{ value: 'join_music_community', label: 'Join a Music Community' },
	{ value: 'collaborate_with_others', label: 'Collaborate with Others' },
	{ value: 'become_a_producer', label: 'Become a Producer' },
	{ value: 'build_an_online_presence', label: 'Build an Online Presence' },
	{ value: 'have_fun_creating', label: 'Have Fun Creating' },
	{ value: 'create_music_for_films', label: 'Create Music for Films' },
	{ value: 'inspire_others_with_music', label: 'Inspire Others with Music' },
	{ value: 'tour_and_perform', label: 'Tour and Perform' },
	{ value: 'create_a_music_label', label: 'Create a Music Label' },
	{ value: 'sell_music', label: 'Sell Music' },
	{ value: 'share_music_online', label: 'Share Music Online' },
	{ value: 'create_music_merchandise', label: 'Create Music Merchandise' },
	{ value: 'release_albums', label: 'Release Albums' },
	{ value: 'achieve_mainstream_success', label: 'Achieve Mainstream Success' },
	{ value: 'collaborate_with_legendary_artists', label: 'Collaborate with Legendary Artists' },
	{ value: 'tour_worldwide', label: 'Tour Worldwide' },
	{ value: 'stay_independent', label: 'Stay Independent' },
	{ value: 'make_impactful_messages', label: 'Make Impactful Messages' },
	{ value: 'create_music_for_ads', label: 'Create Music for Ads' },
	{ value: 'teach_music', label: 'Teach Music' },
	{ value: 'write_for_other_artists', label: 'Write for Other Artists' },
	{ value: 'perform_in_famous_venues', label: 'Perform in Famous Venues' },
	{ value: 'learn_music_theory', label: 'Learn Music Theory' },
	{ value: 'form_a_colaborative_project', label: 'Form a Collaborative Project' },
	{ value: 'create_instagram_music_content', label: 'Create Instagram Music Content' },
	{ value: 'become_a_beatmaker', label: 'Become a Beatmaker' },
	{ value: 'join_a_music_festival', label: 'Join a Music Festival' },
	{ value: 'promote_music_online', label: 'Promote Music Online' },
	{ value: 'collaborate_on_soundtracks', label: 'Collaborate on Soundtracks' },
	{ value: 'find_other_musicians_online', label: 'Find Other Musicians Online' },
	{ value: 'grow_music_collection', label: 'Grow Music Collection' },
	{ value: 'participate_in_jams', label: 'Participate in Jams' },
	{ value: 'build_music_business', label: 'Build Music Business' },
	{ value: 'produce_in_studios', label: 'Produce in Studios' },
	{ value: 'get_signed_to_a_label', label: 'Get Signed to a Label' },
	{ value: 'create_unique_music_ideas', label: 'Create Unique Music Ideas' },
	{ value: 'explore_music_collaborations', label: 'Explore Music Collaborations' }
];

// matchLocations options
export const matchLocationsOptions = [
	{value: 'anywhere', label: 'Anywhere'},
	{value: 'same_city', label: 'Same city'},
	{value: 'same_country', label: 'Same country'},
]

// matchAge (gap) options
export const matchAgeOptions = [
	{ value: "any", label: "Any" },
	{ value: "12-21", label: "12-21" },
	{ value: "22-31", label: "22-31" },
	{ value: "32-41", label: "32-41" },
	{ value: "42-51", label: "42-51" },
	{ value: "52-61", label: "52-61" },
	{ value: "62-71", label: "62-71" },
	{ value: "72-81", label: "72-81" },
	{ value: "82-91", label: "82-91" },
	{ value: "92-101", label: "92-101" },
	{ value: "102-111", label: "102-111" },
	{ value: "112-120", label: "112-120" },
	{ value: "120+", label: "120+" }
]

// matchGender options
export const matchGenderOptions = [
	{ value: "any", label: "Any" },
	{value: 'male', label: 'Male'},
	{value: 'female', label: 'Female'},
	{value: 'other', label: 'Other'}
]

// matchExperience (gap) options
export const matchExperienceOptions = [
	{ value: "any", label: "Any" },
	{ value: "0-2", label: "0-2" },
	{ value: "3-5", label: "3-5" },
	{ value: "6-8", label: "6-8" },
	{ value: "9-11", label: "9-11" },
	{ value: "12-14", label: "12-14" },
	{ value: "15-17", label: "15-17" },
	{ value: "18-20", label: "18-20" },
	{ value: "21-23", label: "21-23" },
	{ value: "24-26", label: "24-26" },
	{ value: "27-29", label: "27-29" },
	{ value: "30-32", label: "30-32" },
	{ value: "33-35", label: "33-35" },
	{ value: "36-38", label: "36-38" },
	{ value: "39-41", label: "39-41" },
	{ value: "42-44", label: "42-44" },
	{ value: "45-47", label: "45-47" },
	{ value: "48-50", label: "48-50" },
	{ value: "50+", label: "50+" }
]
